INSERT INTO
    Guestbook(`GuestbookID`, `Author`, `Message`, `Created`, `AdminComment`)
VALUES
    (1, "JANNE", "HIENOT on sivut!!!", "2006-01-18 18:59:00", ""),
    (2, "Rexhavx", "Eh! what is this all aboot? ;]", "2006-01-19 04:27:00", ""),
    (3, "Reka", "Hienot  sivut,  tulin  muusikot.net  saitilta  katsomaan/rlo", "2006-02-08 09:46:00", ""),
    (4, "Blazingmonga", "Nice site dude! Keep on rocking...", "2006-03-02 01:14:00", ""),
    (5, "Juha", "Enjoy the new guestbook.", "2007-11-03 10:44:00", ""),
    (6, "J-P", "Mielenkiintoista musiikkia, välillä tulee Dan Swanön Crimson II mieleen. Täytyy kyllä ehdottomasti seurailla miten tämä sinun projekti kehittyy, minuun kolahti ja kovaa. Tsemppiä!", "2007-11-27 11:30:00", ""),
    (7, "(no name)", "Melko hyvin yhdeltä mieheltä tämmöinen projekti. Kappaleet eivät niin kovin iske, mutta kuulee kyllä, että on nähty vaivaa!", "2008-03-06 23:10:00", ""),
    (8, "mepis", "Great job man!Congratulations!I'm very impressed!", "2008-04-09 10:55:00", ""),
    (9, "Nmorchyths", "Wow, really good music. A breeze of fresh air in technical/extreme music. Congratulations! (as mepis said)I made some advertisement on smn's metalforums and hope for some response for you. Why don't you sell your stuff?", "2008-04-12 19:16:00", ""),
    (10, "TheLastSucker", "Vortech is fucken awesome!", "2008-04-12 18:04:00", ""),
    (11, "jacktheripper", "I <3 Vortech. Vortech has become one of my all-time favorite metal bands EVER! You know how to produce some kickass music. I <3 the lyric themes (space, end of the world) and the sound is brilliant. Make another Conclusion dude ;). You rock \m/", "2008-04-15 23:19:00", ""),
    (12, "Aleksi", "Kovaa menoa! Meikä tykkää, Torniossa osataan. www.ordogband.com", "2008-05-08 03:06:00", ""),
    (13, "LordD", "Ta muza ma klimat. Dzi ki! :)", "2008-05-16 09:48:00", ""),
    (14, "suleiman", "awesome aweseom music!!! i will hopefully reveiw some of your stuff in 2 weeks time for www.avantgarde-metal.com....you are also featured on my site: http://buruzkh.webs.com keep up the intense metal !", "2008-06-02 13:30:00", ""),
    (15, "Vermillion", "Do you can upload your Demo songs in youtube or last.fm? I can't wait more :D", "2008-08-21 18:48:00", ""),
    (16, "TheLastSucker", "I cannot fucking wait anymore. Your new songs are infinitely awesome. I love You!", "2008-09-01 14:56:00", ""),
    (17, "David", "thanks for your hard work and dedication .. your music is just AWESOME !! .. Keep going like that man you rule !", "2008-09-10 19:18:00", ""),
    (18, "TheLastSucker", "Posthumanism is fucken great but I miss some synths though.", "2008-09-29 16:28:00", ""),
    (19, "Vermillion", "I WANT A NEW SONG!!", "2008-11-23 02:47:00", ""),
    (20, "Juha", "Okay, enjoy the new website and domain!", "2008-12-02 01:24:00", ""),
    (21, "Wintergrindgod", "New website looks great, looking forward to future grinds", "2009-01-04 21:25:00", ""),
    (22, "TheLastSucker", "Xenomorphosis is gorgeous! But I have to admit seriously ( I know you are not even finished with the record!)that your three posted demos slightly sound the same. Don't get me wrong I LOVE them! But I wanted to give you this pointso that you maybe can improve and make the record another magnum opus!", "2009-01-05 14:57:00", ""),
    (23, "Juha", "The three posted songs were written one after another during three days :) The other songs are quite different, but since Xenomorphosis was requested, that's what I uploaded.", "2009-01-05 16:05:00", ""),
    (24, "Wintergrindgod", "pls upload some videoclips ^^", "2009-03-03 15:00:00", ""),
    (25, "TheLastSucker", "I cannot fucking wait anymore for Posthumanism!", "2009-03-08 02:37:00", ""),
    (26, "Jonus", "Posthumanism will rule the earth!!  Vortech = ownage. Better than most crappy signed bands.", "2009-03-25 15:15:00", ""),
    (27, "Jonus", "Juha is genius and kraken has some of the most brutal vocals ever. The conclusion vocals were great also strange electro-whispers, i hope Juha does more like that.", "2009-03-25 15:17:00", ""),
    (28, "TheLastSucker", "Transcendence is a pure epic masterpiece! Posthumanism will be the best album of 2009 without any doubts! \m/", "2009-04-07 21:50:00", ""),
    (29, "David", "Yea some shirts at last!! , a mailorder via your site would be grand :P Cheers \m/", "2009-04-08 14:44:00", ""),
    (30, "Deshoj", "RELEASE IT TODAY I AM SO FUCKING STOKED!!!!!:D", "2009-04-15 18:51:00", ""),
    (31, "TheLastSucker", "I FUCKING LOVE YOU!!! :D I will buy every CD soon when I get my money! Vortech 4 life", "2009-04-16 16:24:00", ""),
    (32, "The Noonster", "Checking you guys out for the first time right now. I am truly amazed, even more so by all the GP tabs you've made available.    Will definitely be purchasing the new album when it's available. Thanks for the kickass Metal.", "2009-04-20 19:32:00", ""),
    (33, "Jonus", "Congrats and thanks to Juha and Kraken for the amazing Posthumanism. Inspirational, otherworldly, amazing.", "2009-05-16 20:39:00", ""),
    (34, "Gerhard", "Great music! I love Biodroid Legions! Also, is there any way I can get an autographed copy of Deep beneath? aegenroth@yahoo.com", "2009-05-30 01:35:00", ""),
    (35, "Ziltoid", "Wow, you really did an excellent job with Posthumanism!  This is easily my favorite album of the year so far, and my favorite industrial-tinged metal album ever!  You truly created a masterpiece with this album, and I've been recommending it whenever possible.  Kudos on creating such a masterpiece!", "2009-06-18 07:51:00", ""),
    (36, "James", "Someone from soulseek showed me you guys, and I have to say, you guys are bruuuuuuutal! Keep it that way fellas! Awesome tunes!", "2009-06-20 15:36:00", ""),
    (37, "[Ukr]", "Thanks for \"Deep Beneath\" guys!  Retribution -the best! Drive yeaah!  Now downloading Posthumanism )", "2009-06-23 19:19:00", ""),
    (38, "TheLastSucker", "Already starting to compose new material? o.O  You are bloody awesome!  Can't fucking wait for a new futuristic armageddon magnum opus! \m/", "2009-06-29 22:52:00", ""),
    (39, "Baz", "You blow me away guys, i just love your sound.", "2009-09-25 00:58:00", ""),
    (40, "Jona", "Frozen Machine is a-mazing. Your composing skills have seemingly transcended mortals. Another album for spring 2010? AWESOME, you manage to make regular great albums that rule, skills! I think you should try some remixes of the best Vortech material, including this. Maybe as ambient/dance track with the epic synths.  If the rest of the album lives up to \"Frozen...\" will definately need to buy it.   HAIL VORTECH!", "2009-11-20 17:49:00", ""),
    (41, "Dmitriy Ukraine", "Hi man!  I like ur music very much! Especially guitar solo is great! Where i can find lyrics? i wanna little karaoke ;)", "2009-12-13 23:53:00", ""),
    (42, "Juha", "All the lyrics are available in the Releases section. There's a link below each album image.", "2009-12-14 11:06:00", ""),
    (43, "Dmitriy Ukraine", "Very interesting lyrics)  Do you read \"Berserker\" by Fred Saberhagen ?", "2009-12-17 21:46:00", ""),
    (44, "Juha", "No, I haven't, but I will check it out, it seems interesting.", "2009-12-18 00:37:00", ""),
    (45, "espo", "Thanks for the discog fellas! absolutely fucking crushing!", "2010-01-04 16:27:00", ""),
    (46, "Dmitriy Ukraine", "Hi man!  Today I listen \"Conclusion\" all my working time non-stop and I think it is most interesting album (no your great's solo, but interesting  songs structure). If you &amp; your friend remake vocals it will be awesome! I hear influences of Fear Factory,but you made it better.  Do you use addictive drums? Or another plugin? I cannot regulate \"kick\" for such good sound...sor for my english)", "2010-01-26 22:58:00", ""),
    (47, "Juha", "On Conclusion, it's just single drum samples triggered with Battery VST.", "2010-01-27 02:21:00", ""),
    (48, "Jona", "The main riff on Conclusions \"Mind Awakening\" is amazing! Vortech is king of industrial metal.", "2010-03-28 22:40:00", ""),
    (49, "Jona", "Looking forward to the next album but no need to rush. Take your time dudes. It will be awesome no doubt.", "2010-04-05 19:56:00", ""),
    (50, "TheLastSucker", "The new song titles for your fifth album are fucking amazing as always. Futuristic space melodies with annihilating armageddon sound. Vortech incinerates! m/", "2010-05-02 20:19:00", ""),
    (51, "Dmitriy Ukraine", "Hi man! Can you upload video about writing \"The Black Rite\"? Solo in video \"Songwriting\" in y-tube is amazing! We're waining for new album!!! Yeeah!  \m/", "2010-05-13 00:07:00", ""),
    (52, "ana", "RELEASE THE KRAKEN", "2010-07-20 22:15:00", ""),
    (53, "Jona", "Looking forward to the next album very much! Goodluck with vocals!", "2010-08-17 22:15:00", ""),
    (54, "Dmitriy", "You did not think about how artificially lower the vocal timbre?? And add some vocoders to growling. I think it should be interesting. D'n'B mix 'the core', I cannot wait anymore!   Lock and load all your vocals  until your fans shall fall by tons )))", "2010-10-17 14:09:00", ""),
    (55, "SurfaceX", "SurfaceX here from Chicago IL USA i dig the atomic amount of energy in your music! your Sybreeds main competition!  V", "2010-11-15 04:24:00", ""),
    (56, "VortechFan", "The faster the BPM, the more I love it! Shedding The Flesh is the best song in the entire world.", "2010-11-24 22:54:00", ""),
    (57, "Didac", "Spain awaits the last release :D", "2010-12-04 04:19:00", ""),
    (58, "Jona", "I hope Matti has got his growling guts ready.", "2010-12-15 18:15:00", ""),
    (59, "Unknown", "Good band, I think they need to work on the riffs a little more.", "2011-07-02 02:36:00", ""),
    (60, "Mataï", "Good and interesting band. Hope you will keep on playing great music. Btw, I'm reviewer and I contact personnally contact Juha in Facebook...hope you receive my message...", "2011-07-09 18:15:00", ""),
    (61, "Jona", "Looking forward to the next album a lot. I think it would be great if you also released backing tracks for the drums and keys maybe? Cheers. Hail Vortech!", "2011-08-21 12:32:00", "Perhaps there will be :) Would be fun to see other people playing some of the songs..."),
    (62, "﻿alexey", "Вы охуенная группа!!! С нетерпением жду ваших новых релизов. Удачи и вдохновения!", "2011-11-01 20:00:00", ""),
    (63, "Lord Malignus", "I featured your music in my podcast show.  http://evolutionrock.podomatic.com", "2012-01-21 06:39:00", "Awesome! Thanks"),
    (64, "Matthew", "Hey guys i was just wondering if y'all are going to release your new album on cd disc? Best regards Matthew", "2012-04-30 00:45:00", ""),
    (65, "Matthew", "Ok i see it has a summer release my bad guys best regards Matthew.", "2012-05-02 04:35:00", ""),
    (66, "AM", "Toimii aina. Devoid of Life iski.<br />www.ordogband.com", "2013-01-16 10:46:00", ""),
    (67, "Matt", "Thanks for the music downloads, will buy a Tee when I got the cash.<br />Keep up the awesome music!", "2013-02-01 17:30:00", ""),
    (68, "Charlie", "Hi! I am currently listening to your \"Devoid of Life\" album. It kicks ass! What do you use for the synths?! It adds awesome atmospheres. Keep rockin' and releasing!", "2013-04-25 21:18:00", "It's mostly Nexus, z3ta+, Imposcar, and MS-20 :)"),
    (69, "J", "Any chance of uploading instrumental versions of past/future albums, some without guitars... Would be great, thanks.", "2013-11-21 20:22:00", "I can do a few different ones, and see how it works :)"),
    (70, "Infineon", "I hope the production/master/mix on the new album is better than on Devoid of Life. That album was very quiet. I'm sure you can do that considering the four releases preceding it had it right.", "2014-01-10 01:09:00", ""),
    (71, "William", "Awesome work! I have no words to describe such work, just ultra-fuckin'-awesome-badass work!", "2014-03-23 21:16:00", ""),
    (72, "just my honest opinion", "\"Vortech - Samples from the next album\" The demo already sounds superior in sound quality and pounds more HARDER and brutal with the drums programmed (could be among the best songs ever in music like Posthumanism, when the production matches the utter sheer brutality). Maybe the final version should be either programmed, or the demos released separately w/ vocals because it's programmed with a drum machine & therefore more brutal (worth it's weight in gold and $30)", "2014-04-03 20:57:00", "Hmm, that's a nice idea! Perhaps a \"double\" album with the same songs with real drums and then with programmed ones."),
    (73, "I agree with the poster below!", "It would be a cool and unique idea to release the album with programmed and real drums, so people can choose what they prefer. I noticed that your demos with programmed drums sound \"fuller\" and more bombastic, which suits the mechanical style of Vortech better in my opinion.", "2014-04-12 06:19:00", "Cool, we will try that on the next album, and see how the response is  :) - Juha"),
    (74, "Infineon", "Juha, I must say that the new song descriptions make my ears all tingly. They sound very promising and I can't wait.<br /><br />Thanks for the insights.", "2014-06-16 00:59:00", ""),
    (75, "Matrix", "You have the exact right idea in the music you do! The faster the blast beats, the better it is! Keep up the great work", "2014-08-25 21:05:00", ""),
    (76, "J", "Looking forward to the next album, will be good to hear the mic and amp combo again. Wasteland is arguably the best of your heavy albums thus far.", "2014-09-14 17:09:00", ""),
    (77, "destroyer", "All of the music is great. The production of the drumming sound in Wasteland and Posthumanism was the most powerful & brutal than everything else, in this discography, and ALL music for that matter. Those songs on Devoid Of Life are amazing, but the potency of the blast beats sounded a little bit more distant, rather than the clear absolute punishing piercing sound of Posthumanism &amp;amp; Wasteland.<br /><br />Entirely a production issue, IMO. A remastered Devoid Of Life could be a game-changer.", "2014-09-22 20:42:00", "Perhaps one day. I do have some plans about re-recording Conclusion with real drums given the opportunity :) - Juha"),
    (78, "Kyle Oleynik", "Hello :)Heavy metal music and rock and roll are some of the greatest choices of music when drinking and eating at the bar.", "2016-10-29 04:44:00", ""),
    (79, "http://www.bagsky.ru", "If the production of this upcoming album is the same as Posthumanism & Wasteland, this will be up there among the very best, and I will be sure to destroy and melt the eardrums of all girls and non-heavy metal fans. If I had time, I'd make music in Cubase also. Just good f'n shit.<br />", "2017-08-01 13:27:00", "That's the plan :) Sharp and sleek futuristic sound.");
