INSERT INTO
  SongsTabs(`Title`, `Filename`, `SongID`)
VALUES
  -- Extinct
  ('Guitar Pro 5', 'Sound Ogre - Life.gp5', 1),
  ('Text-Tab', 'Sound Ogre - Endless Stairs.txt', 2),
  ('Text-Tab', 'Sound Ogre - Evil Never Dies.txt', 3),
  ('Text-Tab', 'Sound Ogre - The Sentence Is Death.txt', 4),
  ('Text-Tab', 'Sound Ogre - Misery.txt', 5),
  -- Asphyxiation
  ('Guitar Pro 5', 'Sound Ogre - Humid Skies of Darkness.gp5', 6),
  ('Guitar Pro 5', 'Sound Ogre - Asphyxiation.gp5', 7),
  ('Guitar Pro 5', 'Sound Ogre - Gnawed by the Otherworldly Vex.gp5', 8),
  ('Guitar Pro 5', 'Sound Ogre - The Variable of Irresolution.gp5', 9),
  ('Guitar Pro 5', 'Sound Ogre - Visions Macabre.gp5', 10),
  ('Guitar Pro 5', 'Sound Ogre - Spiritual Entity.gp5', 11),
  -- Conclusion
  ('Guitar Pro 4', 'Vortech - The Institution.gp4', 12),
  ('Guitar Pro 4', 'Vortech - Terra Ultimatum.gp4', 13),
  ('Guitar Pro 4', 'Vortech - Crescent Moon.gp4', 14),
  ('Guitar Pro 4', 'Vortech - Mind Awakening.gp4', 15),
  ('Guitar Pro 4', 'Vortech - Sentinels of Pain.gp4', 16),
  ('Guitar Pro 4', 'Vortech - Judgement of the Amenti.gp4', 18),
  ('Guitar Pro 4', 'Vortech - Lunar Eclipse.gp4', 19),
  ('Guitar Pro 4', 'Vortech - Sycophant Gods.gp4', 20),
  -- Wasteland
  ('Guitar Pro 4', 'Vortech - The Core.gp4', 22),
  ('Guitar Pro 4', 'Vortech - Evolutionary Project.gp4', 23),
  ('Guitar Pro 4', 'Vortech - Their Contract.gp4', 24),
  ('Guitar Pro 4', 'Vortech - Instigate Hostile Reaction.gp4', 25),
  ('Guitar Pro 4', 'Vortech - Impulse.gp4', 26),
  ('Guitar Pro 4', 'Vortech - Perdition.gp4', 27),
  ('Guitar Pro 5', 'Vortech - Winds of Contamination.gp5', 29),
  ('Guitar Pro 4', 'Vortech - Radiant Storm.gp4', 30),
  -- Deep Beneath
  ('Guitar Pro 4', 'Vortech - The Awakening.gp4', 32),
  ('Guitar Pro 4', 'Vortech - Biodroid Legions.gp4', 33),
  ('Guitar Pro 4', 'Vortech - The Undying Storm.gp4', 34),
  ('Guitar Pro 4', 'Vortech - Shadow Shapes.gp4', 35),
  ('Guitar Pro 4', 'Vortech - Retribution.gp4', 36),
  ('Guitar Pro 4', 'Vortech - Bewildered.gp4', 37),
  ('Guitar Pro 4', 'Vortech - Subjugation.gp4', 39),
  ('Guitar Pro 4', 'Vortech - Exile Within.gp4', 40),
  ('Guitar Pro 4', 'Vortech - So They Rise.gp4', 41),
  -- Posthumanism
  ('Guitar Pro 5', 'Vortech - Posthumanism.gp5', 42),
  ('Guitar Pro 5', 'Vortech - Xenomorphosis.gp5', 43),
  ('Guitar Pro 5', 'Vortech - Destined to Fall.gp5', 44),
  ('Guitar Pro 5', 'Vortech - Humanity Static.gp5', 45),
  ('Guitar Pro 5', 'Vortech - The Wolves.gp5', 46),
  ('Guitar Pro 5', 'Vortech - The New Creations.gp5', 47),
  ('Guitar Pro 5', 'Vortech - Lifeline.gp5', 48),
  ('Guitar Pro 5', 'Vortech - Afterworld.gp5', 49),
  ('Guitar Pro 5', 'Vortech - False Salvation.gp5', 50),
  ('Guitar Pro 5', 'Vortech - Transcendence.gp5', 51),
  ('Guitar Pro 5', 'Vortech - Shedding the Flesh.gp5', 52),
  -- Infocalypse
  ('Guitar Pro 5', 'Vortech - Chaos Dimension.gp5', 53),
  ('Guitar Pro 5', 'Vortech - Charcoal Earth.gp5', 54),
  ('Guitar Pro 5', 'Vortech - Pyre of Souls.gp5', 55),
  ('Guitar Pro 5', 'Vortech - Wire Synapse.gp5', 56),
  -- Devoid of Life
  ('Guitar Pro 5', 'Vortech - The Black Rite.gp5', 57),
  ('Guitar Pro 5', 'Vortech - Neurovirus.gp5', 58),
  ('Guitar Pro 5', 'Vortech - Shattered Cities.gp5', 59),
  ('Guitar Pro 5', 'Vortech - Demon In the Circuitry.gp5', 60),
  ('Guitar Pro 5', 'Vortech - Frozen Machine.gp5', 61),
  ('Guitar Pro 5', 'Vortech - Lost.gp5', 62),
  ('Guitar Pro 5', 'Vortech - Unveiling the Future.gp5', 63),
  ('Guitar Pro 5', 'Vortech - The Apocalypse.gp5', 64),
  -- The Occlusion
  ('Guitar Pro 5', 'Vortech - Forgotten World.gp5', 66),
  ('Guitar Pro 5', 'Vortech - Mechanicide.gp5', 67),
  ('Guitar Pro 5', 'Vortech - The Origin.gp5', 68),
  ('Guitar Pro 5', 'Vortech - Controlled.gp5', 69),
  ('Guitar Pro 5', 'Vortech - MTTF.gp5', 70),
  ('Guitar Pro 5', 'Vortech - Sparks of Ignition.gp5', 71),
  ('Guitar Pro 5', 'Vortech - Flatlined.gp5', 72),
  ('Guitar Pro 5', 'Vortech - Confined.gp5', 73),
  ('Guitar Pro 5', 'Vortech - Beyond Tolerance.gp5', 74),
  ('Guitar Pro 5', 'Vortech - Glitch of Creation.gp5', 75),
  ('Guitar Pro 5', 'Vortech - Below Radar.gp5', 76),
  ('Guitar Pro 5', 'Vortech - Genetic Design.gp5', 77),
  ('Guitar Pro 5', 'Vortech - Legacy System.gp5', 78),
  ('Guitar Pro 5', 'Vortech - Evolutionary Project (Remix).gp5', 79),
  -- Of What Remains
  ('Guitar Pro 5', 'Vortech - Decay to Static.gp5', 80),
  ('Guitar Pro 5', 'Vortech - Disconnect.gp5', 81),
  ('Guitar Pro 5', 'Vortech - Ghosts of Existence.gp5', 82),
  ('Guitar Pro 5', 'Vortech - Strength In Numbers.gp5', 83),
  ('Guitar Pro 5', 'Vortech - Internal Poison.gp5', 84),
  ('Guitar Pro 5', 'Vortech - Oceans of Steel.gp5', 86),
  ('Guitar Pro 5', 'Vortech - Predictable End.gp5', 87),
  ('Guitar Pro 5', 'Vortech - Blast Radius.gp5', 88),
  ('Guitar Pro 5', 'Vortech - Neolithic (The Darkness Is Born).gp5', 89),
  ('Guitar Pro 5', 'Vortech - Underutilized.gp5', 90);
