language: python

python:
- '3.5'

service:
- mysql

before_install:
- pip install -r requirements/dev.txt
- mysql -e 'DROP DATABASE IF EXISTS test_vortech;'
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_vortech;'
- mysql -e 'USE test_vortech;'
- mysql -e 'CREATE USER vortest@localhost IDENTIFIED BY 'tester';'
- mysql -e 'GRANT ALL ON test_vortech.* TO vortest@localhost WITH GRANT OPTION;'
- mysql -e 'FLUSH PRIVILEGES;'

script:
- python -m py.test --cov-report= --cov=backend tests/

after_success:
- coveralls
