language: python

python:
- '3.5'

service:
- mysql

before_install:
- cp settings/secret.sample settings/secret.cfg
- mysql -e 'DROP DATABASE IF EXISTS test_vortech;'
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_vortech;'
- mysql -e 'USE test_vortech;'
- mysql -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'tester';"
- mysql -e 'GRANT ALL ON test_vortech.* TO tester@localhost WITH GRANT OPTION;'
- mysql -e 'FLUSH PRIVILEGES;'

install:
- pip install -r requirements/dev.txt
- python manage.py db upgrade

script:
- python -m pytest --cov-report= --cov=apps tests/

after_success:
- coveralls
