- name: Install MariaDB
  become: yes
  apt:
    name: mariadb-server

- name: Install libmysqlclient-dev
  become: yes
  apt:
    name: libmysqlclient-dev

- name: Install Pip for Ansible
  become: yes
  apt:
    name: python-pip

- name: Install PyMySQL for Ansible
  become: yes
  pip:
    name: pymysql

- name: Create the database
  become: yes
  mysql_db:
    # Using the socket is basically the equivalent of "sudo mysql"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"

- name: Set root user password
  become: yes
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "root"
    password: "{{ mariadb_password }}"
    check_implicit_admin: true

- name: Create the database user with grants
  become: yes
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
