- name: Install MariaDB
  become: yes
  apt:
    name: mariadb-server

- name: Install libmysqlclient-dev
  become: yes
  apt:
    name: libmysqlclient-dev

- name: Create the database user with all grants
  become: yes
  mysql_user:
    login_user: root
    login_password: ""
    name: vortech
    password: "{{ database_password }}"
    priv: '*.*:ALL'
    state: present

- name: Create the database
  become: yes
  mysql_db:
    # Using the socket is basically the equivalent of "sudo mysql"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: vortech
