- name: Create secret.cfg
  become: yes
  copy:
    src: ../files/template-secret.cfg
    dest: /srv/vortech-backend/html/settings/secret.cfg

- name: Secret.cfg - set {{ env }} env
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)env:(.*)$'
    line: 'env: {{ env }}'

- name: Secret.cfg - set {{ env }} secret
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)secret:(.*)$'
    line: 'secret: {{ secret }}'

- name: Secret.cfg - set {{ env }} dialect
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)dialect(.*)$'
    line: 'dialect = {{ db_dialect }}'

- name: Secret.cfg - set {{ env }} driver
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)driver(.*)$'
    line: 'driver = {{ db_driver }}'

- name: Secret.cfg - set {{ env }} host
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)host(.*)$'
    line: 'host = {{ db_host }}'

- name: Secret.cfg - set {{ env }} port
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)port(.*)$'
    line: 'port = {{ db_port }}'

- name: Secret.cfg - set {{ env }} db name
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)database =(.*)$'
    line: 'database = {{ db_name }}'

- name: Secret.cfg - set {{ env }} db username
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)username(.*)$'
    line: 'username = {{ db_username }}'

- name: Secret.cfg - set {{ env }} db password
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)password(.*)$'
    line: 'password = {{ db_password }}'

- name: Secret.cfg - set {{ env }} db charset
  become: yes
  lineinfile:
    path: /srv/vortech-backend/html/settings/secret.cfg
    regexp: '^(.*)charset(.*)$'
    line: 'charset = {{ db_charset }}'

- name: Set the correct rights for secret.cfg
  become: yes
  file:
    path: /srv/vortech-backend/html/settings/secret.cfg
    owner: www-data
    group: www-data
    mode: 0644
