- name: Check if Apache is running
  stat: path=/etc/init.d/apache2
  register: service_status

- name: Stop Apache if it is running
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  register: service_stopped
