---
- hosts: all

- name: Initial setup
  import_playbook: initial/setup.yaml

- name: Database setup
  import_playbook: database/setup.yaml

    # Install the app
    # - include: app/setup.yaml
    # Service setup
    # - include: service/setup.yaml
    # Start the service
    # - include: app/tasks/start.yaml
