---
- name: Create the app directory
  file:
    path: /srv/vortech-backend
    state: directory

- name: Setup virtualenv in the app directory
  # Need to use shell explicitly, to prevent Ansible from using Python 2
  command: python3.6 -m venv /srv/vortech-backend/venv

- import_tasks: app-setup.yml

- name: Make sure app directory grants are OK
  file:
    dest: /srv/vortech-backend
    owner: www-data
    group: www-data
    recurse: yes
