"""Added Shows and related tables

Revision ID: 035f90ef2888
Revises: 9f54657a4536
Create Date: 2017-09-23 22:22:22.875965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f90ef2888'
down_revision = '9f54657a4536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('ShowID', sa.Integer(), nullable=False),
    sa.Column('ShowDate', sa.DateTime(), nullable=False),
    sa.Column('CountryCode', sa.String(length=2), nullable=False),
    sa.Column('Country', sa.String(length=100), nullable=False),
    sa.Column('City', sa.String(length=100), nullable=False),
    sa.Column('Venue', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ShowID')
    )
    op.create_table('ShowsOtherBands',
    sa.Column('ShowsOtherBandsID', sa.Integer(), nullable=False),
    sa.Column('ShowID', sa.Integer(), nullable=False),
    sa.Column('BandName', sa.String(length=200), nullable=False),
    sa.Column('BandWebsite', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ShowID'], ['Shows.ShowID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ShowsOtherBandsID')
    )
    op.create_table('ShowsPeopleMapping',
    sa.Column('ShowsPeopleMappingID', sa.Integer(), nullable=False),
    sa.Column('ShowID', sa.Integer(), nullable=False),
    sa.Column('PersonID', sa.Integer(), nullable=False),
    sa.Column('Instruments', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['PersonID'], ['People.PersonID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ShowID'], ['Shows.ShowID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ShowsPeopleMappingID')
    )
    op.create_table('ShowsSongsMapping',
    sa.Column('SetlistID', sa.Integer(), nullable=False),
    sa.Column('ShowID', sa.Integer(), nullable=False),
    sa.Column('SongID', sa.Integer(), nullable=False),
    sa.Column('SetlistOrder', sa.Integer(), nullable=True),
    sa.Column('ShowSongDuration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ShowID'], ['Shows.ShowID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SongID'], ['Songs.SongID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SetlistID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShowsSongsMapping')
    op.drop_table('ShowsPeopleMapping')
    op.drop_table('ShowsOtherBands')
    op.drop_table('Shows')
    # ### end Alembic commands ###
