"""Added Visitors model

Revision ID: 0f3d4cb9a2fe
Revises: f4e69bc6b067
Create Date: 2017-10-09 18:15:58.750569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3d4cb9a2fe'
down_revision = 'f4e69bc6b067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Visitors',
    sa.Column('VisitID', sa.Integer(), nullable=False),
    sa.Column('VisitDate', sa.DateTime(), nullable=False),
    sa.Column('IPAddress', sa.String(length=20), nullable=True),
    sa.Column('Continent', sa.String(length=20), nullable=True),
    sa.Column('Country', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('VisitID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Visitors')
    # ### end Alembic commands ###
