"""Add song lyrics

Revision ID: 0f8db88d6a30
Revises: c4567eb07fd9
Create Date: 2018-03-23 10:23:44.135107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8db88d6a30'
down_revision = 'c4567eb07fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SongsLyrics',
    sa.Column('SongsLyricsID', sa.Integer(), nullable=False),
    sa.Column('Lyrics', sa.Text(), nullable=False),
    sa.Column('SongID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SongID'], ['Songs.SongID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SongsLyricsID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SongsLyrics')
    # ### end Alembic commands ###
