"""Added Photo Vote model

Revision ID: 1041ee38749d
Revises: ff3c2f0d4024
Create Date: 2018-03-28 00:41:36.236375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1041ee38749d'
down_revision = 'ff3c2f0d4024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VotesPhotos',
    sa.Column('VoteID', sa.Integer(), nullable=False),
    sa.Column('PhotoID', sa.Integer(), nullable=False),
    sa.Column('Vote', sa.Float(precision=2, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['PhotoID'], ['Photos.PhotoID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('VoteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VotesPhotos')
    # ### end Alembic commands ###
