"""Added Tabs model

Revision ID: 325ecf05b3b6
Revises: 8fa899742973
Create Date: 2018-03-24 18:48:24.636225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325ecf05b3b6'
down_revision = '8fa899742973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SongsTabs',
    sa.Column('SongsTabsID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('Filename', sa.String(length=150), nullable=False),
    sa.Column('SongID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SongID'], ['Songs.SongID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SongsTabsID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SongsTabs')
    # ### end Alembic commands ###
