"""Added VotesReleases model

Revision ID: 40be3bb4d9d7
Revises: 0f3d4cb9a2fe
Create Date: 2017-10-11 12:39:51.441885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40be3bb4d9d7'
down_revision = '0f3d4cb9a2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VotesReleases',
    sa.Column('VoteID', sa.Integer(), nullable=False),
    sa.Column('ReleaseID', sa.Integer(), nullable=False),
    sa.Column('Vote', sa.Float(precision=2, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ReleaseID'], ['Releases.ReleaseID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('VoteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VotesReleases')
    # ### end Alembic commands ###
