"""Add UNIQUE to Users columns

Revision ID: 52423311c2b1
Revises: 898acb4b6ac7
Create Date: 2018-04-04 17:22:40.606680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52423311c2b1'
down_revision = '898acb4b6ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ShopItems', 'Price',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=10, asdecimal=True, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('Users', 'Email',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Users', 'Name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('Users', 'Username',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'Users', ['Name'])
    op.create_unique_constraint(None, 'Users', ['Email'])
    op.create_unique_constraint(None, 'Users', ['Username'])
    op.alter_column('VotesPhotos', 'Vote',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('VotesReleases', 'Vote',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('VotesShopItems', 'Vote',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('VotesSongs', 'Vote',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VotesSongs', 'Vote',
               existing_type=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('VotesShopItems', 'Vote',
               existing_type=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('VotesReleases', 'Vote',
               existing_type=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('VotesPhotos', 'Vote',
               existing_type=sa.Float(precision=2, asdecimal=True, decimal_return_scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.alter_column('Users', 'Username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('Users', 'Name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('Users', 'Email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('ShopItems', 'Price',
               existing_type=sa.Float(precision=10, asdecimal=True, decimal_return_scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
