"""Added Shopitem Vote model

Revision ID: 67cef492a609
Revises: ff8f2393e045
Create Date: 2018-03-28 01:22:36.116246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cef492a609'
down_revision = 'ff8f2393e045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VotesShopItems',
    sa.Column('VoteID', sa.Integer(), nullable=False),
    sa.Column('ShopItemID', sa.Integer(), nullable=False),
    sa.Column('Vote', sa.Float(precision=2, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ShopItemID'], ['ShopItems.ShopItemID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('VoteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VotesShopItems')
    # ### end Alembic commands ###
