"""Added model for show comments

Revision ID: 73e15952818c
Revises: d86da395b78a
Create Date: 2018-03-30 04:07:17.445452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e15952818c'
down_revision = 'd86da395b78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CommentsShows',
    sa.Column('CommentID', sa.Integer(), nullable=False),
    sa.Column('ShowID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.Text(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ShowID'], ['Shows.ShowID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CommentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CommentsShows')
    # ### end Alembic commands ###
