"""Removed old news comments model from under News class

Revision ID: 75bb906df167
Revises: af53c49ccce2
Create Date: 2018-03-28 17:44:12.746748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75bb906df167'
down_revision = 'af53c49ccce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NewsComments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewsComments',
    sa.Column('NewsCommentID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('NewsID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('UserID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Comment', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('Created', mysql.DATETIME(), nullable=False),
    sa.Column('Updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['NewsID'], ['News.NewsID'], name='NewsComments_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], name='NewsComments_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('NewsCommentID'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
