"""Added Biography model

Revision ID: 9f54657a4536
Revises: e510b3ad4247
Create Date: 2017-09-23 08:01:26.083658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f54657a4536'
down_revision = 'e510b3ad4247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Biography',
    sa.Column('BiographyID', sa.Integer(), nullable=False),
    sa.Column('Short', sa.Text(), nullable=False),
    sa.Column('Full', sa.Text(), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('BiographyID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Biography')
    # ### end Alembic commands ###
