"""Added Release Reports model

Revision ID: b3e0d6e8b6a3
Revises: 52423311c2b1
Create Date: 2018-04-07 17:24:31.165870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3e0d6e8b6a3'
down_revision = '52423311c2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReleasesReports',
    sa.Column('ReleasesReportsID', sa.Integer(), nullable=False),
    sa.Column('ReleaseID', sa.Integer(), nullable=False),
    sa.Column('Report', sa.Text(), nullable=True),
    sa.Column('Author', sa.String(length=100), nullable=True),
    sa.Column('ReportDate', sa.DateTime(), nullable=True),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ReleaseID'], ['Releases.ReleaseID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReleasesReportsID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReleasesReports')
    # ### end Alembic commands ###
