"""Added Contacts model

Revision ID: ba2285fe624d
Revises: 035f90ef2888
Create Date: 2017-09-26 17:51:30.714304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2285fe624d'
down_revision = '035f90ef2888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacts',
    sa.Column('ContactsID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('TechRider', sa.String(length=100), nullable=True),
    sa.Column('InputList', sa.String(length=100), nullable=True),
    sa.Column('Backline', sa.String(length=100), nullable=True),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ContactsID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Contacts')
    # ### end Alembic commands ###
