"""Added Guestbook model

Revision ID: d255000b4aa6
Revises: ba2285fe624d
Create Date: 2017-09-26 21:11:37.642304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd255000b4aa6'
down_revision = 'ba2285fe624d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Guestbook',
    sa.Column('GuestbookID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Author', sa.String(length=100), nullable=False),
    sa.Column('Message', sa.Text(), nullable=False),
    sa.Column('AdminComment', sa.Text(), nullable=True),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('GuestbookID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Guestbook')
    # ### end Alembic commands ###
