"""Added release-specific song duration

Revision ID: e510b3ad4247
Revises: 09964c92ec59
Create Date: 2017-09-19 23:12:56.216311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e510b3ad4247'
down_revision = '09964c92ec59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ReleasesSongsMapping', sa.Column('ReleaseSongDuration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ReleasesSongsMapping', 'ReleaseSongDuration')
    # ### end Alembic commands ###
