"""Added Song Vote model

Revision ID: ff8f2393e045
Revises: 1041ee38749d
Create Date: 2018-03-28 00:55:46.532275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8f2393e045'
down_revision = '1041ee38749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VotesSongs',
    sa.Column('VoteID', sa.Integer(), nullable=False),
    sa.Column('SongID', sa.Integer(), nullable=False),
    sa.Column('Vote', sa.Float(precision=2, asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('Updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SongID'], ['Songs.SongID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('VoteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VotesSongs')
    # ### end Alembic commands ###
